spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:1106/basicBoard"
    username: root
    password: root
    auto-commit: false

server:
  port: 7070

jpa:
  database-platform: org.hibernate.dialect.MYSQL5InnoDBDialect
  open-in-view: false
  show-sql: true
  hibernate:
    format_sql: true
    ddl-auto: create
    order_inserts: true
    order_updates: true


