spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:1106/basicBoard"
    username: root
    password: root
    auto-commit: false
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
      order_inserts: true
      order_updates: true
    open-in-view: false

server:
  port: 7070

logging:
  level:
    root: INFO
    com.example.basicboard: DEBUG

